[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health/"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
startCommand = "bash -c '(sleep 5 && python manage.py migrate_schemas --shared && python manage.py migrate_schemas && python manage.py setup_public_tenant && python manage.py create_superuser_if_needed && python manage.py create_demo_gym --members 100) & exec gunicorn gym_management.wsgi --bind 0.0.0.0:$PORT --workers 2 --log-file -'"
